version: '{build}'
clone_depth: 3 
environment:  
  matrix:
    - job_name: java8-linux-x86-64-deploy
      appveyor_build_worker_image: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      DEPLOY: 1
    - job_name: java11-linux-x86-64
      appveyor_build_worker_image: Ubuntu2004
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64/
    - job_name: java8-win-x64
      appveyor_build_worker_image: Visual Studio 2017
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - job_name: java11-win-x64
      appveyor_build_worker_image: Visual Studio 2017
      JAVA_HOME: C:\Program Files\Java\jdk11
  OSSRH_USERNAME:
    secure: 64k8xKR++oDsn//bh82FAg==
  OSSRH_PASSWORD:
    secure: zcn8sBdPWDa/IVJr+uwUYDkH0YXufEkx9TZendXeu1Y=      
matrix:
  fast_finish: true
install:
  - bash -c "mkdir -p $HOME/.m2"
build: Script  
build_script:
  - mvn install -DskipTests=true -U -B
test_script:
  - mvn test -Dassembly.skipAssembly=true -B
deploy_script:
  - bash -c "if [ ${DEPLOY} ]; then mvn source:jar deploy --settings .ci-settings.xml -DskipTests=true -B; fi"   
cache:
  - $HOME/.m2/